project:
  type: website
  output-dir: _site

website:
  title: "Data Analysis Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
  search: true
  
format:
  html:
    theme: cosmo
    toc: true

